# Generated by Django 4.0.3 on 2022-03-19 21:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('genre', models.CharField(max_length=14)),
                ('slug', models.CharField(max_length=130)),
            ],
        ),
    ]
