# Generated by Django 4.0.3 on 2022-03-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('ans', models.CharField(max_length=2)),
            ],
        ),
    ]
